### ISSUE TITLE
Plugin architecture overhaul

### ISSUE THREAD

**Issue by hsoft** [hsoft/moneyguru#401]
Plugins came very late in moneyGuru's design and, even then, they were implemented in a "cobble something together and see if it holds".

@brownnrl in #26 is building something that involves new plugins and the shortcomings of the system as a whole are becoming unbearable. It's time to design the thing a little better.

Here's a list of problems with the current system:
## All activated by default

As soon as a plugin is present in the plugins folder, it's activated. It's not always a desirable situation and one has to manually remove/put back files in there to manage plugins.

We need a new view that allows us to list plugins and activate them from within moneyGuru.
## No versioning

We have no way of managing plugin updates and we don't know for which version of moneyGuru plugins were designed. The second part doesn't matter much yet because the plugin API hasn't moved (it hasn't been used!), but if we're serious about having a proper plugin API, we might as well handle versions properly.

The "plugin update" part is already a problem though with plugin examples. The plugin folder, when it doesn't exist, is created and then automatically populated with the examples bundled in moneyGuru. If the folder already exists however, we don't touch it. The result of that is that updates to plugin examples aren't effective until the user wipes his plugin folder.

**Comment by brownnrl** [comment]
How would you feel about using a ``zope.interface`` style system (or exactly that) for plugins?  Where functionality isn't indicated by an ``isinstance`` call, but by a ``InterfaceName.implementedBy(klass)`` type of check?

Then, you would have plugins that looked like...

```python
class MyPlugin(Plugin):
    implements(IImportAction)

    def can_perform_action(...):
        [...]

    def perform_action(...):
        [...]
```

Not sure how it would all work with current inheritance.  But an aspect to consider for plugin architecture.

**Comment by hsoft** [comment]
It's an interesting possibility if we end up with a lot of plugin types. But if we were to take that road, I'd be more inclined to use [Python's ABC](https://docs.python.org/3/library/abc.html) rather than `zope.interface`.

**Comment by hsoft** [comment]
Slowly but surely walking the path towards pluginification. I plan to implement #451 for the next release (2.10)

**Comment by hsoft** [comment]
I'll scale back on this. Nobody ever wrote an external plugin, it's not worth maintaining an API. I'll slowly close the API and integrate existing plugin directly in moneyGuru's code.

Also, for having recently worked within the newly designed import structure, it's way too complicated now and much of this complexity is simply to allow arbitrary plugins to plug arbitrary features in. Let's stop this.

**Comment by hsoft** [comment]
By the way, sorry @brownnrl I know you worked a lot on this plugin design, but the complexity it brought to the code was just too much for plugins to be worth it. As I strip the thing, I see the code simplify and it's a breath of fresh air.

Had plugins been used, it might have been worth it, but since it wasn't, this complexity is just a weight holding the project down.

**Comment by brownnrl** [comment]
I completely understand.  In truth, I’m glad you are not only still developing moneyguru but taking it in a consolidating direction.  Choosing a select set of features and not having multiple supported platforms (beyond the feature sets already provided by Qt) will probably increase adoption.

I’ve been using moneyguru twice a month with full solid coverage of my family’s finances since mid-way through 2016.  I feel guilty my contributions dropped off completely a few years ago, work and home life picked up and I found my free hours dwindling.  With the import plugin I just started doing way more development work than actually importing transactions, and the trade off didn’t seem worth it.

But I would like to help again where I can.  I do have a few bugs to note, and I echo @tuxlifan in thinking that an envelop / zero sum budget system would be a killer feature.
