### ISSUE TITLE
Importing transactions does not update the UI properly

### ISSUE THREAD

**Issue by brownnrl** [hsoft/moneyguru#418]
On ``master`` with a new document, make the first action you do an import.  You'll notice that there is not an option to undo your import in the main menu.  Tested on ``master`` back ``2.7.2`` to ``2.8.2``.

Tested on cocoa, importing updates the UI fine (qt still doesn't work on the Mac though).

I have a PR for this (generating a ticket number for the commit first I'll reference the PR afterwards) but you should review it I'm not sure 100% why it works.  :)

If it could be twitter-length explanation that doesn't take a lot of time, I'd love to hear why as well.

**Comment by brownnrl** [comment]
See PR #419.

**Comment by brownnrl** [comment]
Also, from my tests, making the change doesn't affect Mac cocoa side.  I was worried maybe it was hooked into the "transaction_changed" vs "transactions_changed", but it seems fine either way.

**Comment by hsoft** [comment]
Good catch, thanks. The explanation you want is why the bug doesn't happen on OS X? My guess is because menu items under Cocoa are *always* generated on-the-fly whereas in Qt, they're generated once and we update it from time to time (for example, when we catch a `transactions_updated`). Cocoa doesn't need to be told that it has to refresh its menus because it always does.

I can't accept the patch as-is though. It's core code and the fact that there was a bug is an indication of a lack of test coverage. I'll write one right now.

**Comment by hsoft** [comment]
Well, we still fix a bug in Cocoa with this! Let's follow the deer trail together:

1. https://github.com/hsoft/moneyguru/blob/master/core/gui/main_window.py#L674
2. https://github.com/hsoft/moneyguru/blob/master/core/gui/main_window.py#L611
3. https://github.com/hsoft/moneyguru/blob/master/qt/controller/main_window.py#L685
4. https://github.com/hsoft/moneyguru/blob/master/qt/controller/main_window.py#L685

Alright, so now we understand why the Undo menu isn't updated in Qt. If we do the same in Cocoa:

1. https://github.com/hsoft/moneyguru/blob/master/cocoa/mg_cocoa.py#L1140
2. https://github.com/hsoft/moneyguru/blob/master/cocoa/controllers/MGMainWindowController.m#L648

Now, we see that this signal has indeed nothing to do with Undo menu refreshing under Cocoa, but that we're still missing document dirtiness updating.

I'll update the title of the ticket.

**Comment by hsoft** [comment]
Pushed your fix and a test.

**Comment by brownnrl** [comment]
Thank you for the explanation, it's clear (or at least much more clear than it was).  :)
