### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type TableView has been deleted

### ISSUE THREAD

**Issue by bru65pag** [hsoft/moneyguru#471]
Application Name: moneyGuru
Version: 2.10.2

Traceback (most recent call last):
  File "/usr/share/moneyguru/qt/controller/table.py", line 107, in appPrefsChanged
    self._updateFontSize(prefs=self.sender())
  File "/usr/share/moneyguru/qt/controller/table.py", line 95, in _updateFontSize
    font = self.view.font()
RuntimeError: wrapped C/C++ object of type TableView has been deleted

**Comment by bf-pepe** [comment]
distro: debian testing 
de:mate 1.20.2

i can replicate this error, changing font size in --> view --> preferences --> font size. whats weird is that i did not have this issue in ubuntu 16.04, i recently switched to debian testing, and now fields increase / decrease show bad numeric format, instead of 3.00, display 3. , this gets worse when values are low, like 0.45, displays as 0. see screenshots.
![font-10](https://user-images.githubusercontent.com/44693584/47897732-27a94000-de30-11e8-985f-b5174b542720.jpg)
![font-11](https://user-images.githubusercontent.com/44693584/47897733-2841d680-de30-11e8-958a-97b0c0236793.jpg)
![font-12](https://user-images.githubusercontent.com/44693584/47897736-2841d680-de30-11e8-97f6-5b32ed14715f.jpg)

**Comment by hsoft** [comment]
The font display issue was fixed through #501, the crash, I have troubles reproducing it.

**Comment by bf-pepe** [comment]
i too cant reproduce the error. could be due to a python update in debian buster
