### ISSUE TITLE
Dragging Pane to Far Right Crash

### ISSUE THREAD

**Issue by brownnrl** [hsoft/moneyguru#481]
Hi!  Sorry I've been off the radar, kids and what not.

Related to fc071ff (which I was coming to create an issue for, but you pre-empted so thank you! :) ).  If you move a tab to the last position you get a crash with the following stack.  This is on the Windows side (which I know you don't support anymore), but it will likely replicate on the Linux side.  I'll test that later to confirm.

```
Application Name: moneyGuru
Version: 2.10.2

Traceback (most recent call last):
  File "C:\Users\nelson brown\projects\mguru\moneyguru\qt\controller\main_window.py", line 637, in tabMoved
    self.model.move_pane(fromIndex, toIndex, refresh_panes=False)
  File "C:\Users\nelson brown\projects\mguru\moneyguru\core\gui\main_window.py", line 394, in move_pane
    pane = self.panes[pane_index]
IndexError: list index out of range
```

**Comment by wolfpackmars2** [comment]
Confirmed on Linux. To duplicate, drag a pane beyond the "+" (add new pane button).
The pane will then be after the plus, and clicking on any panes after the add new pane button will cause other crashes.

**Comment by wolfpackmars2** [comment]
Ok, so I created a pull request which appears to fix the crash, but still allows the tab to be moved beyond the "add tab" button.  I've hit a wall here - not sure how to fix this (guidance appreciated @hsoft) :)

**Comment by hsoft** [comment]
@wolfpackmars2 I've answered in the PR itself. As I wrote, I don't think that the approach is the correct one, but I really appreciate the contribution! I'm not really sure of what to do exactly, but my guess would be that we have to look into Qt's doc and see if there's a way to tell it which dragging position are allowed (so that we can tell it "anything but the last one"). I'll try to look into the issue soon.
